# Generated by Django 5.0.7 on 2024-07-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('social_media_alias', models.CharField(max_length=255)),
                ('ssm_no', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('F&B', 'F&B'), ('Non-F&B', 'Non-F&B')], max_length=20)),
                ('certificate', models.FileField(upload_to='certificates/')),
                ('product_picture', models.ImageField(upload_to='product_pictures/')),
                ('menu', models.FileField(upload_to='menus/')),
                ('equipment', models.CharField(max_length=255)),
            ],
        ),
    ]
