# Generated by Django 5.0.7 on 2024-07-15 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='equipment',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='MarketApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('SILVER', 'SILVER'), ('GOLD', 'GOLD'), ('PLATINUM', 'PLATINUM')], max_length=20)),
                ('certificate', models.FileField(upload_to='certificates/')),
                ('equipment_list', models.FileField(upload_to='equipment_lists/')),
                ('approved', models.BooleanField(default=False)),
                ('proof_of_payment', models.FileField(blank=True, default=None, null=True, upload_to='proof_of_payments/')),
                ('booth_no', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.market')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
    ]
