# Generated by Django 5.0.7 on 2024-07-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_market_remove_vendor_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
