# Generated by Django 5.0.7 on 2024-07-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_user_vendor_verified_alter_vendor_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketapplicant',
            name='equipment_list',
            field=models.CharField(max_length=255),
        ),
    ]
